module.exports = function () {
  return {
  products: [
  { id: 1, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 275, image: "assets/bags/1.jpg" },
  { id: 2, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 190, image: "assets/bags/2.jpg"  },
  { id: 3, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 225, image: "assets/bags/3.jpg" },
  { id: 4, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 280, image: "assets/bags/4.jpg"  },
  { id: 5, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 250, image: "assets/bags/5.jpg" },
  { id: 6, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 290, image: "assets/bags/6.jpg"  },
  { id: 7, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 225, image: "assets/bags/7.jpg" },
  { id: 8, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 250, image: "assets/bags/8.jpg"  },
  { id: 9, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 275, image: "assets/bags/9.jpg" },
  { id: 10, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 230, image: "assets/bags/10.jpg"  },
  { id: 11, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 225, image: "assets/bags/11.png" },
  { id: 12, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 260, image: "assets/bags/12.jpg"  },
  { id: 13, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 275, image: "assets/bags/13.jpg" },
  { id: 14, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 290, image: "assets/bags/14.jpg"  },
  { id: 15, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 225, image: "assets/bags/15.jpg" },
  { id: 16, name: "Leather Bag", category: "bags",
  description: "Genuine Leather Bag", price: 275, image: "assets/bags/16.jpg"  },
  { id: 17, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 275, image: "assets/belts/1.jpg" },
  { id: 18, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 190, image: "assets/belts/2.jpg"  },
  { id: 19, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 225, image: "assets/belts/3.jpg" },
  { id: 20, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 280, image: "assets/belts/4.jpg"  },
  { id: 21, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 250, image: "assets/belts/5.jpg" },
  { id: 22, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 290, image: "assets/belts/6.jpg"  },
  { id: 23, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 225, image: "assets/belts/7.jpg" },
  { id: 24, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 250, image: "assets/belts/8.jpg"  },
  { id: 25, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 275, image: "assets/belts/9.jpg" },
  { id: 26, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 230, image: "assets/belts/10.jpg"  },
  { id: 27, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 225, image: "assets/belts/11.jpg" },
  { id: 28, name: "Leather Belt", category: "belts",
  description: "Genuine Leather Belt", price: 260, image: "assets/belts/12.jpg"  },
  { id: 30, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 190, image: "assets/watchStraps/2.jpg"  },
  { id: 31, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 225, image: "assets/watchStraps/3.jpg" },
  { id: 32, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 280, image: "assets/watchStraps/4.jpg"  },
  { id: 33, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 250, image: "assets/watchStraps/5.jpg" },
  { id: 34, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 290, image: "assets/watchStraps/6.jpg"  },
  { id: 35, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 225, image: "assets/watchStraps/7.jpg" },
  { id: 36, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 250, image: "assets/watchStraps/8.jpg"  },
  { id: 37, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 275, image: "assets/watchStraps/9.jpg" },
  { id: 38, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 230, image: "assets/watchStraps/10.jpg"  },
  { id: 39, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 225, image: "assets/watchStraps/11.jpg" },
  { id: 40, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 260, image: "assets/watchStraps/12.jpg"  },
  { id: 41, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 275, image: "assets/watchStraps/18.jpg" },
  { id: 42, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 290, image: "assets/watchStraps/14.jpg"  },
  { id: 43, name: "Leather Strap", category: "straps",
  description: "Genuine Leather Strap", price: 225, image: "assets/watchStraps/15.jpg" },
  { id: 45, name: "Leather Wallet", category: "wallets",
  description: "Genuine Leather Wallet", price: 175, image: "assets/wallets/1.jpg"  },
  { id: 46, name: "Leather Wallet", category: "wallets",
  description: "Genuine Leather Wallet", price: 150, image: "assets/wallets/2.jpg"  },
  { id: 47, name: "Leather Wallet", category: "wallets",
  description: "Genuine Leather Wallet", price: 125, image: "assets/wallets/3.jpg"  },
  { id: 48, name: "Leather Wallet", category: "wallets",
  description: "Genuine Leather Wallet", price: 135, image: "assets/wallets/4.jpg"  },
  { id: 49, name: "Leather Wallet", category: "wallets",
  description: "Genuine Leather Wallet", price: 175, image: "assets/wallets/5.jpg"  }
],
orders: []
}
}
